# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name : Configure AWS creds
      uses : aws-actions/configure-aws-credentials@v1
      with : 
        role-to-assume : ${{vars.AWS_ROLE_ARN}}
        aws-access-key-id	: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key	: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region	: "us-east-1"

    - name: run python
      run: |
        # pythin main.py
        python main.py
